version: '3'
services:
    app:
        container_name: app
        working_dir: /app
        build:
            context: ./
            dockerfile: ./Dockerfile.dev
        image: ghornon/nodejs-test-app.dev
        environment:
            PORT: 8080
            DATABASE_IP: mongo
            DATABASE_PORT: 27017
            DATABASE_USER: root
            DATABASE_PASSWORD: password
            FORCE_COLOR: 1
        ports:
            - 8080:8080
        depends_on:
            - mongo
        volumes:
            - ./:/app
    mongo:
        container_name: db
        image: mongo
        ports:
            - 27017:27017
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: password
        volumes:
            - mongodb:/data/db
            - mongodb_config:/data/configdb
volumes:
    mongodb:
    mongodb_config:
