- hosts: nodes
  become: yes
  tasks:
  - name: Ensure docker is installed
    apt:
      name: docker.io
      state: latest

  - name: Ensure docker-compose is installed
    apt:
      name: docker-compose
      state: latest

  - name: Add user to docker group
    user:
      name: vagrant
      groups: docker
  - name: Run docker-compose
    shell:
      cmd: "docker-compose up --build -d"
      chdir: /vagrant/docker/node

- hosts: swarm-manager
  tasks:
    - name: Create primary swarm manager
      shell: docker swarm init --advertise-addr {{ ansible_default_ipv4.address }}
      when: "docker_info.stdout.find('Swarm: inactive') > 0"

    - name: Get docker swarm manager ip
      copy:
        content: '{{ ansible_default_ipv4.address }}'
        dest: '/tmp/dsm_ip'

    - name: Get docker swarm manager token
      shell: docker swarm join-token -q manager
      register: swarm_manager_token
    - copy:
        content: '{{ swarm_manager_token.stdout }}'
        dest: '/tmp/dsm_mt'

    - name: Get docker swarm worker token
      shell: docker swarm join-token -q worker
      register: swarm_worker_token
    - copy:
        content: '{{ swarm_worker_token.stdout }}'
        dest: '/tmp/dsm_wt'

- hosts: nodes
  tasks:
    - name: Join nodes to the swarm
      shell: "docker swarm join --token {{ lookup('file', '/tmp/dsm_mt') }} {{ lookup('file', '/tmp/dsm_ip') }}:2377"
      when: "docker_info.stdout.find('Swarm: inactive') > 0"
      retries: 5
      delay: 5
