- hosts: nodes
  become: yes
  tasks:
  - name: Ensure docker is installed
    apt:
      name: docker.io
      state: latest

  - name: Ensure docker-compose is installed
    apt:
      name: docker-compose
      state: latest

  - name: Add user to docker group
    user:
      name: vagrant
      groups: docker

  - name: Leave swarms
    shell: "docker swarm leave -f"
    ignore_errors: yes

- hosts: swarm-manager
  tasks:

    - name: Create primary swarm manager
      shell: docker swarm init --advertise-addr 172.16.1.51

    - name: Get docker swarm manager ip
      copy:
        content: '172.16.1.51'
        dest: '/vagrant/tmp/dsm_ip'

    - name: Get docker swarm manager token
      shell: docker swarm join-token -q manager
      register: swarm_manager_token
    - copy:
        content: '{{ swarm_manager_token.stdout }}'
        dest: '/vagrant/tmp/dsm_mt'

    - name: Get docker swarm worker token
      shell: docker swarm join-token -q worker
      register: swarm_worker_token

    - copy:
        content: '{{ swarm_worker_token.stdout }}'
        dest: '/vagrant/tmp/dsm_wt'

- hosts: swarm-workers
  tasks:
    - name: Join nodes to the swarm
      shell: "docker swarm join --token {{ lookup('file', '/vagrant/tmp/dsm_mt') }} {{ lookup('file', '/vagrant/tmp/dsm_ip') }}:2377"

- hosts: nodes
  tasks:
    - name: Create service
      shell: "docker service create --name nodeapp --publish 8080:8080 ghornon/nodejs-test-app"

    - name: Scale service
      shell: "docker service sale nodeapp=3"
